# Generated by Django 3.0 on 2020-07-31 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0002_auto_20200731_1450'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CloseBet',
            new_name='ClosedBet',
        ),
    ]
