# Generated by Django 3.0 on 2020-07-31 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0003_auto_20200731_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchresult',
            options={'verbose_name_plural': 'matches'},
        ),
    ]
