# Generated by Django 3.0 on 2020-07-31 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0004_auto_20200731_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'matches'},
        ),
        migrations.AlterModelOptions(
            name='matchresult',
            options={},
        ),
    ]
