# Generated by Django 3.0 on 2020-07-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0005_auto_20200731_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='datetime_match',
            field=models.DateTimeField(null=True),
        ),
    ]
